[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pysco"
version = "0.2.1"
authors = [
    { name = "Michel-Andrès Breton", email = "michel-andres.breton@obspm.fr" },
]
description = "A Python library to run N-body simulations with modified gravity"
readme = "README.md"
requires-python = ">=3.6"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "astropy",
    "pyfftw",
    "numba",
    "pandas",
    "scipy",
    "pyarrow",
    "h5py",
]

[project.urls]
Homepage = "https://github.com/mianbreton/pysco"
